name: Webpage to PDF

on:
  workflow_dispatch:

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert Webpage to PDF
      uses: rockbenben/webpage-to-pdf-action@v1
      with:
        url: 'https://yourwebsite.com'   # Replace with your site
        output: 'output.pdf'

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: webpage-pdf
        path: output.pdf
