name: Webpage to PDF

on:
  workflow_dispatch:  # Allows manual run from GitHub UI
  push:
    branches: [ main ]  # Optional: runs on push to main branch

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert Webpage to PDF
      uses: rockbenben/webpage-to-pdf@v1
      with:
        url: 'https://yourwebsite.com'  # Replace with your website URL
        output: 'output.pdf'

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: webpage-pdf
        path: output.pdf
